connector.name=elasticsearch
elasticsearch.host=${ENV:ELASTICSEARCH_HOST}
elasticsearch.port=${ENV:ELASTICSEARCH_PORT}
elasticsearch.default-schema-name=default
elasticsearch.security=PASSWORD
elasticsearch.auth.user=${ENV:ELASTICSEARCH_USER}
elasticsearch.auth.password=${ENV:ELASTICSEARCH_PASSWORD}
elasticsearch.ignore-publish-address=true
elasticsearch.request-timeout=30s
elasticsearch.connect-timeout=10s
